### PR TITLE
Key release event

### PR DESCRIPTION
**Pull request by therealjumbo**
I'm still testing this, but I wanted to get your feedback on if you like this approach.

### CODE REVIEW

**Comment by therealjumbo** [comment]
I force pushed a couple times because my commit messages were slightly wrong, fixed.

**Comment by sergey-dryabzhinsky** [comment]
I don't quite understand what you are trying to achieve

**Comment by therealjumbo** [comment]
That's a good question. So my problem is this: I have displays with no mouse, keyboard or touchscreen. On all my devices the browser is the only app running, and it is fullscreen and borderless. However, since there is mouse or touchscreen input mode (only 8 buttons on the bottom below the screen) when the browser starts the MainWindow has the focus, not the view. So since that is the case, without 
```
void MainWindow::keyReleaseEvent(QKeyEvent *event)
{
    view->event(event);
}
```
The view doesn't see keyrelease events. So with that function, the issue then becomes that when I do have a touchscreen or mouse, then the view gets two keyrelease events (and similarly gets two keypress events, which I never understood why until now). So this still doesn't work right for both modes. I'm going to keep messing around with it until I figure something out that works for both cases. Unless you have any ideas that would help?

**Comment by therealjumbo** [comment]
FYI I'm using https://w3c.github.io/uievents/tools/key-event-viewer.html to test. I'm assuming the results on that page are correct.

**Comment by therealjumbo** [comment]
This page gives different results: https://unixpapa.com/js/testkey.html. I'll try to get the results on this page match the results for that page if I use firefox and chrome for both modes of the qt-webkit-kiosk browser (i.e. when I have the view in focus and when I don't).

**Comment by therealjumbo** [comment]
@sergey-dryabzhinsky, this now works as expected. For both the focused case (with a touchscreen or mouse) or the unfocused case (with no touchscreen or mouse) the javascript engine now only sees one keypress event for each physical keypress, and similarly sees one keyrelease event for each physical keyrelease. 

Are you good with merging this as is, or would you like me to explain why I made these changes more?

**Comment by sergey-dryabzhinsky** [comment]
If webview not focused (how?) - it will not get events fallthrough mainwindow?

**Comment by HED-jzignego** [comment]
> If webview not focused (how?)

It's not focused since there is no way to focus it on devices without a touchscreen or mouse.

>  it will not get events fallthrough mainwindow?

It sorta did before, but there were two bugs. The first thing to keep in mind, is that the behavior is different in the focused and unfocused case.

The first bug, was that in the focused case, due to my earlier modifications, the view got a double copy of each keypress event. One copy from the Qt engine, since it has the StrongFocus policy, and one copy from the `MainWindow:keyPress` function when that function called `view->event(event);`

The second bug, was that in the unfocused case, the view didn't get a keyrelease event at all. 

So that's why the fixes here always say:
```
        if (! view->hasFocus()) {
            view->event(event);
        }
```
So that way we don't send the event, if the view has the focus since if the view has the focus, it already gets the event from the Qt Engine.

**Comment by HED-jzignego** [comment]
@sergey-dryabzhinsky just another ping on this PR.

**Comment by sergey-dryabzhinsky** [comment]
Ok. Let's try this.

**Comment by HED-jzignego** [comment]
Thanks !!!

**Pull request merged**
